export enum UnitAssignmentOptions {
  UnitId = "UnitId",
  EquipmentTypeId = "EquipmentTypeId",
  Settings = "Settings",
  Location = "Location",
  Purpose = "Purpose",
  Description = "Description",
  Circuit = "Circuit",
  Panel = "Panel",
  ControlType = "Control.Type",
  Universe = "Control.DMXUniverse",
  Address = "Control.DMXAddress",
  LCIO = "LCIO",
  Accessories = "Accessories",
  Channel = "Channel",
  Filter = "Filter",
  Pattern = "Pattern",
  SetupNotes = "SetupNotes",
  InstallNotes = "InstallNotes",
  LastImported = "LastImported",
  ExternalID = "ExternalID",
  ExternalVersionGuid = "ExternalVersionGuid",
  InternalNotes = "InternalNotes",
  Notes = "Notes",
}

export const AssignableUnitOptions = [
  { label: "ControlType", value: UnitAssignmentOptions.ControlType },
  { label: "Unit Id", value: UnitAssignmentOptions.UnitId },
  { label: "Description", value: UnitAssignmentOptions.Description },
  { label: "Purpose", value: UnitAssignmentOptions.Purpose },
  { label: "Filter", value: UnitAssignmentOptions.Filter },
  { label: "Pattern", value: UnitAssignmentOptions.Pattern },
  { label: "Internal Notes", value: UnitAssignmentOptions.InternalNotes },
  { label: "Universe", value: UnitAssignmentOptions.Universe },
  { label: "Address", value: UnitAssignmentOptions.Address },
  { label: "Notes", value: UnitAssignmentOptions.Notes },
  { label: "Circuit", value: UnitAssignmentOptions.Circuit },
  { label: "Panel", value: UnitAssignmentOptions.Panel },
  { label: "Location", value: UnitAssignmentOptions.Location },
  { label: "Setup Notes", value: UnitAssignmentOptions.SetupNotes },
  { label: "Install Notes", value: UnitAssignmentOptions.InstallNotes },
  { label: "Channel", value: UnitAssignmentOptions.Channel },
  { label: "Equipment Type", value: UnitAssignmentOptions.EquipmentTypeId },
  { label: "LCIO", value: UnitAssignmentOptions.LCIO },
  { label: "Accessories", value: UnitAssignmentOptions.Accessories },
  { label: "Settings", value: UnitAssignmentOptions.Settings },
  { label: "LastImported", value: UnitAssignmentOptions.LastImported },
  { label: "UniqueRevitId", value: UnitAssignmentOptions.ExternalID },
  { label: "RevitVersionId", value: UnitAssignmentOptions.ExternalVersionGuid },
];
